########This script allows the user to create a CDF file based on Water Surface Elevations developed
########in the createWSE.R code.  You must generate a WSE file first to run this code.
########Writen by Andrew Schwarz, Delta Stewardship Council
########Last Updated 10/16/2020

library(tidyverse)

###User Input: call a list of WSE files previously generated by the createWSE.R code
Scenarios<-c("Hist_0_SACcapped", "2050_1_SACcapped")

for(sen in Scenarios){
   
  WSE<-read.csv(paste0("Data/WSE/", sen, ".csv"))
  CDF<-data.frame(matrix(nrow=429, ncol=26))
  CDF[,1]<-colnames(WSE)
  colnames(CDF)<-c("Node", 0.99, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01, 0.005, 0.004, 0.003, 0.002, 0.001, 0.0001)
  for(i in 1:nrow(CDF)){
        CDF[i,2:26]<-quantile(WSE[,i] ,probs=(1-as.numeric(c( 0.99, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01, 0.005, 0.004, 0.003, 0.002, 0.001, 0.0001)))) 
        }
      write.csv(CDF, file=paste0("Data/WSE/CDF/", sen, ".csv"), row.names = F)
}



####################Calculate and Map Differences between CDFs#############################################
###This part of the code is an extra function that is not necessary to run.  This lets the user compare any
###two CDFs generated by the above code to compare and map differences in water levels between the two conditions
###SPECIAL CARE MUST BE TAKEN IN FILE SAVING AND MAP LABELING.  THIS CODE IS NOT DYNAMICALLY FLEXIBLE.  THE USER
###MUST CONFIGURE THE GGPLOT AESTHETICS FOR THEIR NEEDS.

library(sf)
Scenario1<-"Hist_0"
Scenario2<-"2050_0"


levee_pts<- st_read("./Data/DSM2NodesSLRstage.shp")
levee_pts$Node<- paste0("Node_",levee_pts$nodenum)
levee_lines<- st_read("./Data/DLISIslands.shp")

    CDFTableName1<-Scenario1
    CDFTableName2<-Scenario2
    CDF1<- read.csv(paste0("C:/Users/aschwarz/deltacouncil/Delta Adapts Project - Documents/Data and Modeling/Flooding Analysis/Data/DSC-Generated/WSE/CDF/CDF_", CDFTableName1, ".csv"))
    CDF2<- read.csv(paste0("C:/Users/aschwarz/deltacouncil/Delta Adapts Project - Documents/Data and Modeling/Flooding Analysis/Data/DSC-Generated/WSE/CDF/CDF_", CDFTableName2, ".csv"))
diffCDF<- CDF2[,2:26]-CDF1[,2:26]
diffCDF<-cbind(CDF1[,1], diffCDF)
colnames(diffCDF)<-c("Node", "Diff0.99", "Diff0.9", "Diff0.8", "Diff0.7", "Diff0.6", "Diff0.5", "Diff0.4", "Diff0.3", "Diff0.2", "Diff0.1", "Diff0.09", "Diff0.08", "Diff0.07", "Diff0.06", "Diff0.05", "Diff0.04", "Diff0.03", "Diff0.02", "Diff0.01", "Diff0.005", "Diff0.004", "Diff0.003", "Diff0.002", "Diff0.001", "Diff0.0001")
levee_pts<- left_join(levee_pts, diffCDF)

ggplot()+geom_sf(data=levee_lines)+geom_sf(data=levee_pts, aes(color=Diff0.01))+
  scale_color_stepsn(breaks=c(.5,1,2),colors= c("Blue", "Green", "Yellow", "Red"), name="Change in\nWater Level (ft)")+
  ggtitle("Calaveras River Influence Throughout the Delta\nCapped versus Uncapped Flows (15,000 cfs)")+
  theme_void()

#ggsave(file="./Output/WSEchangeSJR_2.png")


